CREATE TABLE CMDUSE
(
	CMDID INTEGER NOT NULL,
	MODULEID INTEGER NOT NULL,
	METHODID INTEGER NOT NULL,
	FOREIGN KEY (CMDID) REFERENCES COMMAND(ID),
	FOREIGN KEY (MODULEID) REFERENCES MODULE(ID),
	FOREIGN KEY (METHODID) REFERENCES METHOD(ID)
)