CREATE TABLE COMMANDS
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CMD text NOT NULL,
	FULLTYPEOBJECT text not null,
	MODULENAME text not null
);

INSERT INTO COMMANDS (CMD, MODULENAME, FULLTYPEOBJECT) VALUES ('HELLO', 'SYSTEM', '');
INSERT INTO COMMANDS (CMD, MODULENAME, FULLTYPEOBJECT) VALUES ('EXIT', 'SYSTEM', '');
INSERT INTO COMMANDS (CMD, MODULENAME, FULLTYPEOBJECT) VALUES('HUMEUR', 'SYSTEM', '');
INSERT INTO COMMANDS (CMD, MODULENAME, FULLTYPEOBJECT) VALUES('OFF', 'SYSTEM', '');
INSERT INTO COMMANDS (CMD, MODULENAME, FULLTYPEOBJECT) VALUES('ON', 'SYSTEM', '');
INSERT INTO COMMANDS (CMD, MODULENAME, FULLTYPEOBJECT) VALUES ('CONTEXT', 'SYSTEM', '');
INSERT INTO COMMANDS (CMD, MODULENAME, FULLTYPEOBJECT) VALUES ('LOAD CONTEXT', 'SYSTEM', '');
INSERT INTO COMMANDS (CMD, MODULENAME, FULLTYPEOBJECT) VALUES ('READMAIL', 'EMAIL','EmailPlug.ImapProvider'); 