CREATE TABLE COMMANDS
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CMD text NOT NULL,
	MODULENAME text not null
);

INSERT INTO COMMANDS (CMD, MODULENAME) VALUES ('HELLO', 'SYSTEM');
INSERT INTO COMMANDS (CMD, MODULENAME) VALUES ('EXIT', 'SYSTEM');
INSERT INTO COMMANDS (CMD, MODULENAME) VALUES('HUMEUR', 'SYSTEM');
INSERT INTO COMMANDS (CMD, MODULENAME) VALUES('OFF', 'SYSTEM');
INSERT INTO COMMANDS (CMD, MODULENAME) VALUES('ON', 'SYSTEM');
INSERT INTO COMMANDS (CMD, MODULENAME) VALUES ('CONTEXT', 'SYSTEM');
INSERT INTO COMMANDS (CMD, MODULENAME) VALUES ('LOAD CONTEXT', 'SYSTEM');