CREATE TABLE MODULES (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME text NOT NULL UNIQUE,
	DLL text UNIQUE,
	ACTIVE INTEGER,
	VERS text NOT NULL
);
INSERT INTO MODULES (NAME, DLL, ACTIVE, VERS) VALUES ('SYSTEM', NULL, 1,'0.0.1');