CREATE TABLE TRIGGERCMD
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	SENID INTEGER NOT NULL,
	CMDID INTEGER NOT NULL,
	MODULENAME text NOT NULL,
	FOREIGN KEY(SENID) REFERENCES SENTENCES(SENID),
	FOREIGN KEY(CMDID) REFERENCES COMMANDS(ID),
	FOREIGN KEY (MODULENAME) REFERENCES MODULE (NAME)
);
CREATE UNIQUE INDEX IndexUnique on TRIGGERCMD (SENID, CMDID, MODULENAME);

INSERT INTO TRIGGERCMD (CMDID, SENID, MODULENAME) VALUES (1,1, 'SYSTEM'),(1,2, 'SYSTEM'),(1,3, 'SYSTEM'),(1,4, 'SYSTEM');
insert into TRIGGERCMD (SENID, CMDID, MODULENAME) values (5, 2, 'SYSTEM'), (6,2,'SYSTEM'), (7,2,'SYSTEM');
insert into TRIGGERCMD (SENID, CMDID, MODULENAME) values (8, 3, 'SYSTEM'), (9,3,'SYSTEM'), (10,3,'SYSTEM');
insert into TRIGGERCMD (SENID, CMDID, MODULENAME) values (11, 4, 'SYSTEM'), (12,4,'SYSTEM'),(13,5,'SYSTEM');
insert into TRIGGERCMD (SENID, CMDID, MODULENAME) values (14, 6, 'SYSTEM'), (15,6,'SYSTEM'), (16,6,'SYSTEM');
insert into TRIGGERCMD (SENID, CMDID, MODULENAME) values (17, 7, 'SYSTEM'),(18,7,'SYSTEM');