CREATE TABLE TRIGGERCMD
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	SENID INTEGER NOT NULL,
	CMDID INTEGER NOT NULL,
	MODULENAME text NOT NULL,
	FOREIGN KEY(SENID) REFERENCES SENTENCES(SENID),
	FOREIGN KEY(CMDID) REFERENCES COMMANDS(ID),
	FOREIGN KEY (MODULENAME) REFERENCES MODULE (NAME)
);
CREATE UNIQUE INDEX IndexUnique on TRIGGERCMD (SENID, CMDID, MODULENAME);

INSERT INTO TRIGGERCMD (CMDID, SENID, MODULENAME) VALUES (1,1, 'SYSTEM'),(1,2, 'SYSTEM'),(1,3, 'SYSTEM'),(1,4, 'SYSTEM');